services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mebudget
      POSTGRES_PASSWORD: mebudget
      POSTGRES_DB: mebudget
    ports:
      - "5432:5432"
    volumes:
      - mebudget-pg:/var/lib/postgresql/data

volumes:
  mebudget-pg:
